---
:dataminer_definition: product_code_column_names
:multiselect:
  :product_types:
    :url: "/settings/products/link_product_code_column_names/$:id$"
    :preselect: "SELECT product_column_name_id AS id FROM product_types_product_code_column_names WHERE product_type_id = $:id$"
    :section_caption: "SELECT 'Select product code columns'"
    :can_be_cleared: false
    :multiselect_save_remote: true
    :conditions: product_type
:conditions:
  :product_type:
    - :col: product_types_product_column_names.product_type_id
      :op: =
      :val: $:id$
