---
:dataminer_definition: product_types
:actions:
- :url: "/settings/products/product_types/$:id$"
  :text: view
  :icon: fa-eye
  :title: View
  :popup: true
- :url: "/settings/products/product_types/$:id$/edit"
  :text: edit
  :icon: fa-edit
  :title: Edit
  :popup: true
- :url: "/settings/products/product_types/$:id$"
  :text: delete
  :icon: fa-remove
  :is_delete: true
  :popup: true
- :url: "/list/product_column_names/multi?key=product_types&id=$:id$"
  :text: product columns
  :icon: fa-list
  :popup: true
- :url: "/list/product_code_column_names/multi?key=product_types&id=$:id$"
  :text: product code columns
  :icon: fa-list
  :popup: true
- :url: "/settings/products/reorder_product_code_column_names/$:id$"
  :text: order product code columns
  :icon: fa-list
  :popup: true
:page_controls:
- :control_type: :link
  :url: "/settings/products/product_types/new"
  :text: New Product Type
  :style: :button
  :behaviour: :popup
