= Grid actions
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== Grid actions

Actions provide a context menu of actions that can be associated with a row in a grid.
They are specified in `list` or `search` yaml files.
These appear when the `list` button in the `action` column of a grid row is clicked.
The actions are rendered as a context menu that can include submenu groupings.

=== Example

[source,yaml]
----
:actions:
  - :url: /path/to/resource
    :text: action item text
    :icon: fa-edit
    :title: The dialog title with $:id$ in it
    :popup: true
    :auth:
      :function: function_name
      :program: program_name
      :permission: required_permission
    :hide_if_null: another_field_id
  - :separator: true
  - submenu:
     :text: Submenu caption
     :items:
       - :url: /path/to/this/resource
         :text: A submenu item
----

=== Top-level items

The `:actions:` section is an array of top-level items.
These tiems can be one of:

* An action
* A separator line
* A submenu

=== Actions

An action is a Hash of attributes which is an item in the actions array.

|===
|key |value |description

|:url
|A URL.
a|Framework paths start with a `/`. Any value from the grid row can be included in the path by specifying it surrounded by dollar signs and prefixed with a colon.

e.g. to include the `customer_id` in the URL when the link is clicked: `/customers/$:customer_id$`.

See <<URLs>> below for more information.

|:text
|Link text.
|The text to display for the link. Defaults to `'link'`.

|:icon
|icon's css class name.
a|Currently the system uses FontAwesome icons - e.g.:

* view: fa-eye
* edit: fa-edit
* new: fa-plus-circle
* delete: fa-remove
* list/associations: fa-list
* sort: fa-sort
* restrict: fa-lock

|:popup
|`true` or `false`
|If `true`, the link will be opened in a popup dialog. If `false` or not present, the link will open in a new page.

|:title
|Dialog title.
a|Text to show as the caption of a popup dialog. Only makes sense if `:popup` is true.

If the text includes a column name within `$:...$` delimiters, that part of the title will be repaced with the column value of the selected row.

e.g. `A dialog for grade $:grade$ fruit` would render as `A dialog for grade 1X fruit` if the grade coumn of the current row's value was `1X`.

|:title_field
|Name of a field in the grid.
|The value in the named field of the selected grid row will be used as the popup dialog title.

|:hide_if_null
|Name of a field in the grid.
|The item will not appear if the named field's value is null.

|:hide_if_present
|Name of a field in the grid.
|The item will not appear if the named field's value is NOT null.

|:hide_if_true
|Name of a field in the grid.
|The item will not appear if the named field's value is `true`.

|:hide_if_false
|Name of a field in the grid.
|The item will not appear if the named field's value is `false`.

|:is_delete
|`true` or `false`
a|If `true`, a prompt dialog will force the user to choose OK to continue or Cancel.

The link will be POSTed to the server with `_method` = `'DELETE'` if the user chooses OK.

**NB** for this to be a `fetch` call, the `:popup` value must also be `true`.

|:prompt
|Text - a question to ask the user.
|If present, a prompt dialog will show this text, asking the user to choose OK to continue or Cancel.

|:auth
|A Hash with `:function`, `:program` and `:permission` keys.
a|If the user does not have the required permission, the link will not appear.

This is usually used when an action requires a special level of authorisation -- not so much for basic CRUD authorisations (which are almost implied by the fact that the user can call the list action and thus has permission to at least view the applicable program).

|===

=== Separators

Separators take the form of `:separator: true`. The value is irrelevant -- a separator will be rendered if the key `:separator:` is present with any value.

=== Submenus

Submenus are sub-groupings of actions. Submenus have an items array that can contain actions, separators and other submenus.

[source,yaml]
----
:submenu:
  :text: Submenu title         # <1>
  :items:                      # <2>
----
<1> This text appears in the context menu with a right-pointing arrowhead.
<2> Items is an array of items just like under <<Actions>>. These appear to the right of the arrowhead.

=== URLs

URL strings are relative to the root and start with a `/`.

Tokens (`$:xxx$`) in the URL are replaced by their matching column values in the selected row. Here `$:xxx$` will be replaced by the value in the `xxx` column of the selected row.

*List* URLS start with `/list/` and are followed by the filename without extension of the list to render. e.g. `/list/users` will render the grid defined in `grid_definitions/lists/users.yml`.

*Search* URLS start with `/search/` and are followed by the filename without extension of the search to render. e.g. `/search/users` will render the grid defined in `grid_definitions/searches/users.yml`.

There are a few _special_ URLs that link to other grids to render a *filtered* list or a *multiselect* list.

==== Link to a filtered list

Create a link like this to link to a grid that is filtered in some way by values in the current row.

Add `with_params?key=KEYNAME&id=$:id$` at the end of the URL to render a list that has a `:conditions` section named `KEYNAME` and has a `col` entry for `id`.
[source,yaml]
----
- :url: "/list/user_program_permissions/with_params?key=standard&id=$:id$"
----

Then in the `user_program_permissions.yml` file in the `list` directory:
[source,yaml]
----
:dataminer_definition: user_program_permissions # <1>
:conditions:
  :standard:                                    # <2>
    - :col: pu.user_id                          # <3>
      :op: =                                    # <4>
      :val: $:id$                               # <5>
----
<1> The dataminer query definition in `grid_definitions/dataminer_queries/`.
<2> This matches the value of `key` in the URL.
<3> The name of a parameter in the query definition specified in (1).
<4> The operator to apply (=, <, > etc.)
<5> The value to apply. Matches `$:id$` in the calling URL which will be set to the `id` column of the selected row in the grid.

==== Link to a multiselect grid

Create a link like this to link to a grid that presents multiselect choices. The grid can be filtered by parameter(s) in the link, and/or it can have pre-selections made based on parameter(s) in the link.

add `multi?key=KEYNAME&id=$:id$` to render a list that has a `:multiselect` section named `KEYNAME`.

[source,yaml]
----
- :url: "/list/users/multi?key=progfunc_users&id=$:id$"
----

Then in the `users.yml` file in the `list` directory:
[source,yaml]
----
:multiselect:
  :progfunc_users:
    :url: "/security/functional_areas/program_functions/link_users/$:id$"
    :preselect: "SELECT user_id AS id FROM program_functions_users WHERE program_function_id = $:id$"
    :section_caption: "SELECT 'Assign users to ' || program_function_name FROM program_functions WHERE id = $:id$"
    :can_be_cleared: true
----
OR
[source,yaml]
----
- :url: "/list/user_program_permissions/multi?key=set_group&id=$:id$"
----
Then in the `user_program_permissions.yml` file in the `list` directory:
[source,yaml]
----
:multiselect:
  :set_group:
    :url: "/development/masterfiles/users/set_permissions/$:id$"
    :section_caption: "Set permissions for programs"
    :multiselect_save_method: dialog
    :conditions:
      - :col: pu.user_id
        :op: =
        :val: $:id$
----

Possible options in the `:multiselect` section:
[source,yaml]
----
:multiselect:
  :keyname:                                              # <1>
    :url: "/path/to/call/on/save"                        # <2>
    :section_caption: "SELECT statement or fixed string" # <3>
    :preselect: "SELECT statement"                       # <4>
    :multiselect_save_method: dialog/remote/http         # <5>
    :can_be_cleared: true                                # <6>
    :conditions:                                         # <7>
      - :col: param.column
        :op: =
        :val: $:id$
----
<1> Keyname to match `?key=` part of calling URL.
<2> The path to be called when the user saves a selection.
<3> Caption can be a `SELECT` query that returns the caption (using tokens from the URL) or a fixed string.
<4> A `SELECT` statement that returns an `id` column. Matching ids in the grid will be pre-selected.
<5> Optional. How to save -- defaults to `http` which sends a POST request.
    `remote` will send a `POST fetch` request.
    `dialog` will send a `GET fetch` request that will render in a modal dialog.
<6> Optional. Can the user select no rows at all (to clear a previous selection). Default is `false`.
<7> Conditions to apply to filter the grid. Same as per filtered lists (above).

