doc_seqs_po_number:
  db_sequence_name: doc_seqs_po_number
  data_type: :integer
  table: mr_purchase_orders
  column: purchase_order_number
doc_seqs_delivery_number:
  db_sequence_name: doc_seqs_delivery_number
  data_type: :integer
  table: mr_deliveries
  column: delivery_number
doc_seqs_sku_number:
  db_sequence_name: doc_seqs_sku_number
  data_type: :integer
  table: mr_skus
  column: sku_number
doc_seqs_stock_adjustment_number:
  db_sequence_name: doc_seqs_stock_adjustment_number
  data_type: :integer
  table: mr_bulk_stock_adjustments
  column: stock_adjustment_number
doc_seqs_waybill_number:
  db_sequence_name: doc_seqs_waybill_number
  data_type: :integer
  table: mr_deliveries
  column: waybill_number
doc_seqs_tripsheet_number:
  db_sequence_name: doc_seqs_tripsheet_number
  data_type: :integer
  table: vehicle_jobs
  column: tripsheet_number
doc_seqs_credit_note_number:
  db_sequence_name: doc_seqs_credit_note_number
  data_type: :integer
  table: mr_goods_returned_notes
  column: credit_note_number
dummy_invoice:
  db_sequence_name: doc_seqs_inv
  data_type: :string
  prefix: INV
  digit_length: 7
  table: invoices
  column: invoice_ref
