doc_seqs_po_number:
  db_sequence_name: doc_seqs_po_number
  data_type: :integer
  prefix: PO
  digit_length: 7
  table: mr_purchase_orders
  column: purchase_order_number
doc_seqs_delivery_number:
  db_sequence_name: doc_seqs_delivery_number
  data_type: :integer
  prefix: DEL
  digit_length: 7
  table: mr_deliveries
  column: delivery_number
dummy_invoice:
  db_sequence_name: doc_seqs_inv
  data_type: :string
  prefix: INV
  digit_length: 7
  table: invoices
  column: invoice_ref