---
:caption: Material Resource Type Configs
:sql: "SELECT \"material_resource_type_configs\".\"id\", \"material_resource_types\".type_name,\r\n
  \ \"material_resource_sub_types\".\"sub_type_name\",\r\n  \"material_resource_type_configs\".\"product_code_separator\",
  \"material_resource_type_configs\".\"has_suppliers\",\r\n  \"material_resource_type_configs\".\"has_marketers\",
  \"material_resource_type_configs\".\"has_retailer\",\r\n  \"material_resource_type_configs\".\"active\",
  \"material_resource_type_configs\".\"created_at\",\r\n  \"material_resource_type_configs\".\"updated_at\",
  \"material_resource_type_configs\".\"material_resource_sub_type_id\"\r\nFROM \"material_resource_type_configs\",
  \"material_resource_types\", \"material_resource_sub_types\"\r\n  WHERE material_resource_sub_types.id
  = material_resource_type_configs.material_resource_sub_type_id\r\n  AND material_resource_types.id
  = material_resource_sub_types.material_resource_type_id"
:limit: 
:offset: 
:columns:
  id:
    :name: id
    :sequence_no: 1
    :caption: Id
    :namespaced_name: material_resource_type_configs.id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  type_name:
    :name: type_name
    :sequence_no: 2
    :caption: Type name
    :namespaced_name: material_resource_types.type_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  sub_type_name:
    :name: sub_type_name
    :sequence_no: 3
    :caption: Sub type name
    :namespaced_name: material_resource_sub_types.sub_type_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_code_separator:
    :name: product_code_separator
    :sequence_no: 4
    :caption: Product code separator
    :namespaced_name: material_resource_type_configs.product_code_separator
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  has_suppliers:
    :name: has_suppliers
    :sequence_no: 5
    :caption: Has suppliers
    :namespaced_name: material_resource_type_configs.has_suppliers
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  has_marketers:
    :name: has_marketers
    :sequence_no: 6
    :caption: Has marketers
    :namespaced_name: material_resource_type_configs.has_marketers
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  has_retailer:
    :name: has_retailer
    :sequence_no: 7
    :caption: Has retailer
    :namespaced_name: material_resource_type_configs.has_retailer
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  active:
    :name: active
    :sequence_no: 8
    :caption: Active
    :namespaced_name: material_resource_type_configs.active
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  created_at:
    :name: created_at
    :sequence_no: 9
    :caption: Created at
    :namespaced_name: material_resource_type_configs.created_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  updated_at:
    :name: updated_at
    :sequence_no: 10
    :caption: Updated at
    :namespaced_name: material_resource_type_configs.updated_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  material_resource_sub_type_id:
    :name: material_resource_sub_type_id
    :sequence_no: 11
    :caption: Material resource sub type
    :namespaced_name: material_resource_type_configs.material_resource_sub_type_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
:query_parameter_definitions:
- :column: material_resource_type_configs.material_resource_sub_type_id
  :caption: Material resource sub type
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 1
  :list_def: SELECT sub_type_name, id FROM material_resource_sub_types ORDER BY sub_type_name
